// <copyright file="Given_Auto_Generated_MapDefinition.cs" company="million miles per hour ltd">
// Copyright (c) 2013-2014 All Right Reserved
// 
// This source is subject to the MIT License.
// Please see the License.txt file for more information.
// All other rights reserved.
// 
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
// </copyright>

using NUnit.Framework;

namespace KodeKandy.Mapnificent.Tests.MapperTests
{
    [TestFixture]
    public class Given_Auto_Generated_MapDefinition
    {
        [Test]
        public void When_()
        {
            // Arrange
            //  var sut = new ClassMap(ProjectionType.Create<SimpleFrom, SimpleTo>());

            // Act

            // Assert
            // TODO: how to we check bindings for each field?
            // sut.GetMemberBindingDefinition()
        }

        [Test]
        public void When_Validating_AutoGenerated_Map_Then_Maps()
        {
            // Arrange
//            var sut = new ClassMap(ProjectionType.Create<SimpleFrom, SimpleTo>());
//            var schema = new Mapper();
//
//            // Act
//            sut.Validate(schema);

            // Assert
        }
    }
}