using NUnit.Framework;

namespace KodeKandy.Mapnificent.Tests.MapperTests
{
    [TestFixture]
    public class Given_Auto_Generated_MapDefinition
    {
        [Test]
        public void When_()
        {
            // Arrange
          //  var sut = new Map(ProjectionType.Create<SimpleFrom, SimpleTo>());

            // Act

            // Assert
            // TODO: how to we check bindings for each field?
            // sut.GetMemberBindingDefinition()
        }

        [Test]
        public void When_Validating_AutoGenerated_Map_Then_Maps()
        {
            // Arrange
//            var sut = new Map(ProjectionType.Create<SimpleFrom, SimpleTo>());
//            var schema = new Mapper();
//
//            // Act
//            sut.Validate(schema);

            // Assert
        }
    }
}